{% set name = "inline-model-metrics" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/inline_model_metrics-{{ version }}.tar.gz
  sha256: f979bf1d1ccef43fe2127ef4e338db1178da02af752edb15836795b6bbf2fed7

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.6,<3.10
    - pip
  run:
    - python >=3.6,<3.10
    - metoffice-afterburner
    - iris
    - netcdf4
    - numpy
    - tempest-helper

test:
  imports:
    - inline_model_metrics

about:
  home: https://github.com/MetOffice/inline_model_metrics
  summary: inline_model_metrics is a package to to run model metrics inline with a climate model.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jonseddon
    - robertsmalcolm
